#include"header.h"
#include"prototype.h"
int compression5(int fd1,char *ma)
{	
	int i,fd,j=0,sl;
	unsigned char ch,copy1,copy2,*fn,c,byt;
	sl=strlen(ma);
	fd=(*fp4)("com5");
	lseek(fd1,0,SEEK_SET);
	while(1)
	{
		byt=byt^byt;
		read(fd1,&ch,1);
		if(ch==10)
		{
			byt=byt^byt;
			byt=byt|0xF0;
			(*fp8)(byt,fd);
		}
		for(i=0;i<sl;i++)
		{
			if(ma[i]==ch)
			{
				j=i;
				break;
			}
		}
		sprintf(&c,"%c",j);	
		c=c<<3;
		byt=byt|c;
//							printf("byt1:=%d\n",byt);
		read(fd1,&ch,1);
		if(ch==10)
		{
			byt=byt^byt;
			byt=byt|0xF0;
			(*fp8)(byt,fd);
			break;
		}
		for(i=0;i<sl;i++)
		{
			if(ma[i]==ch)
			{
				j=i;
				break;
			}
		}
		sprintf(&c,"%c",j);
		c=c<<3;
		copy1=c;
		c=c>>5;
		byt=byt|c;
							printf("1byt2:=%d\n",byt);
		(*fp8)(byt,fd);
		byt=byt^byt;
		copy1=copy1<<3;
		byt=byt|copy1;
//							printf("byt3:=%d\n",byt);
		read(fd1,&ch,1);
		if(ch==10)
		{
			byt=byt^byt;
			byt=byt|0xF0;
			(*fp8)(byt,fd);
			break;
		}
		for(i=0;i<sl;i++)
		{
			if(ma[i]==ch)
			{
				j=i;
				break;
			}
		}
		sprintf(&c,"%c",j);
//							printf("c:=%d\n",c);
		c=c<<3;
//							printf("c:=%d\n",c);
		c=c>>2;
//							printf("c:=%d\n",c);
		byt=byt|c;
//							printf("byt4:=%d\n",byt);
		read(fd1,&ch,1);
		if(ch==10)
		{
			byt=byt^byt;
			byt=byt|0xF0;
			(*fp8)(byt,fd);
			break;
		}
		for(i=0;i<sl;i++)
		{
			if(ma[i]==ch)
			{
				j=i;
				break;
			}
		}
		sprintf(&c,"%c",j);
		c=c<<3;
		copy1=c;
		c=c>>7;
		byt=byt|c;
							printf("2byt5:=%d\n",byt);
//		printf("byt3:=%d\n",byt);
		(*fp8)(byt,fd);
		byt=byt^byt;
		copy1=copy1<<1;
		byt=byt|copy1;
//							printf("byt6:=%d\n",byt);
		read(fd1,&ch,1);
		if(ch==10)
		{
			byt=byt^byt;
			byt=byt|0xF0;
			(*fp8)(byt,fd);
			break;
		}
		for(i=0;i<sl;i++)
		{
			if(ma[i]==ch)
			{
				j=i;
				break;
			}
		}
		sprintf(&c,"%c",j);
		c=c<<3;
		copy1=c;
		c=c>>4;
		byt=byt|c;
							printf("3byt7:=%d\n",byt);
//		printf("byt3:=%d\n",byt);
		(*fp8)(byt,fd);
		byt=byt^byt;
		copy1=copy1<<4;
		byt=byt|copy1;
//		byt=byt|c;
//							printf("byt8:=%d\n",byt);
		read(fd1,&ch,1);
		if(ch==10)
		{
			byt=byt^byt;
			byt=byt|0xF0;
			(*fp8)(byt,fd);
			break;
		}
		for(i=0;i<sl;i++)
		{
			if(ma[i]==ch)
			{
				j=i;
				break;
			}
		}
		sprintf(&c,"%c",j);
		c=c<<3;
		c=c>>1;
		byt=byt|c;
//							printf("byt9:=%d\n",byt);
		read(fd1,&ch,1);
		if(ch==10)
		{
			byt=byt^byt;
			byt=byt|0xF0;
			(*fp8)(byt,fd);
			break;
		}
		for(i=0;i<sl;i++)
		{
			if(ma[i]==ch)
			{
				j=i;
				break;
			}
		}
		sprintf(&c,"%c",j);
		c=c<<3;
		copy1=c;
		c=c>>6;
		byt=byt|c;
							printf("4byt10:=%d\n",byt);
//		printf("byt3:=%d\n",byt);
		(*fp8)(byt,fd);
		byt=byt^byt;
		copy1=copy1<<2;
		byt=byt|copy1;
//							printf("byt11:=%d\n",byt);
		read(fd1,&ch,1);
		if(ch==10)
		{
			byt=byt^byt;
			byt=byt|0xF0;
			(*fp8)(byt,fd);
			break;
		}
		for(i=0;i<sl;i++)
		{
			if(ma[i]==ch)
			{
				j=i;
				break;
			}
		}
		sprintf(&c,"%c",j);
		c=c<<3;
		c=c>>3;
		byt=byt|c;
							printf("5byt12:=%d\n",byt);
		(*fp8)(byt,fd);
	}
	return 0;
}
