int* mainmenu();
int* (*fp1)();
int compression();
int (*fp2)();
char* filename();
char* (*fp3)();
int openfile(char *);
int (*fp4)(char *);
char* readfile(int);
char* (*fp5)(int);
char* masterarray(int);
char* (*fpma)(int);
int unique(int,char,char *);
int (*fp6)(int,char,char *);
int insert(int,int,int,char*,char);
int (*fp7)(int,int,int,char*,char);
int writefile(char,int);
int (*fp8)(char,int);
int codelenth(int);
int (*fp9)(int);
int compression2(int,char *);
int (*fp10)(int,char *);
int compression3(int,char *);
int (*fp11)(int,char *);
int compression4(int,char *);
int (*fp12)(int, char *);
int compression5(int,char *);
int (*fp13)(int,char *);
int compression6(int,char *);
int (*fp14)(int,char *);
int compression7(int,char *);
int (*fp15)(int,char *);
int decompression();
int (*fp16)();
int decompression2(int,char *);
int (*fp17)(int,char *);
int decompression3(int,char *);
int (*fp18)(int,char *);
int decompression4(int,char *);
int (*fp19)(int,char *);
int decompression5(int,char *);
int (*fp20)(int,char *);
int decompression6(int,char *);
int (*fp21)(int,char *);
int decompression7(int,char *);
int (*fp22)(int,char *);
int (*arr_of_func_ptr[2])();

